typography_spectrum: 0.908891674829647
color:
  brandStrength: 0.354796931380406
  lightness: 0.9713998544029891
  saturation: 0.2551698796451092
  rhythmicContrast: 0.7564508391078562
  brandColors:
    - '#5B594C'
    - '#7C7D75'
    - '#0F1417'
    - '#D8DCDF'
    - '#D8AD9C'
layout_spectrum: 0.2625475940294564
author:
  name: Matthew Nordloh
  email: matthewnordloh@hotmail.com
name: matthewnordloh
title: Another Beautiful Day!
description: 'Good Things Always Work Out...If You Let Them:)'
